version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Check Node version
          command: node --version

      - run:
          name: Check Docker version
          command: docker version

      - run:
          name: Build Docker Image
          command: docker build -t rtemurbek/react-docker -f Dockerfile.dev .

      - run:
          name: Run Tests
          command: docker run rtemurbek/react-docker npm run test -- --coverage
  deploy:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout

      - run:
          name: Update packages
          command: sudo apt-get update

      - run:
          name: Install AWS CLI
          command: sudo apt-get install -y awscli

      - run:
         name: Install Elastic Beanstalk CLI
         command: sudo apt-get install -y python3-pip && pip3 install awsebcli

      - run:
          name: Configure AWS CLI
          command: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set region $AWS_REGION

      - run:
          name: Deploy to Elastic Beanstalk
          command: eb deploy Docker-react-env-1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

      - deploy:
          filters:
            branches:
              only:
                - main
