version: 2.1

jobs:
  build:
    docker:
      - image: node:alpine
    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: docker build -t rtemurbek/react-docker -f Dockerfile.dev .

      - run:
          name: Run Tests
          command: docker run rtemurbek/react-docker npm run test -- --coverage
