version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout

      - run:
          name: Check Node version
          command: docker version

      - run:
          name: Check Docker version
          command: docker version

      - run:
          name: Build Docker Image
          command: docker build -t rtemurbek/react-docker -f Dockerfile.dev .

      - run:
          name: Run Tests
          command: docker run rtemurbek/react-docker npm run test -- --coverage
